# Generated by Django 4.2.2 on 2023-06-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='datetime_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
