# Generated by Django 4.2.2 on 2023-06-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('savepassword', '0002_savepasswordmodel_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='savepasswordmodel',
            name='site',
            field=models.CharField(default='Dj', max_length=2000),
            preserve_default=False,
        ),
    ]
