# Generated by Django 4.2.2 on 2023-06-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='role_name',
            field=models.CharField(max_length=2000, unique=True),
        ),
    ]
