# Generated by Django 4.2.2 on 2023-06-15 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_alter_rolemodel_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='datetime_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
